#!/bin/bash

do_build=
verbose=

prompt() {
    while true; do
        read -r -p "Continue (Y/n)? " yn
        case $yn in
            Y|y ) do_build=1; break;;
            "" ) do_build=1; break;;
            N|n ) do_build=0; break;;
            * ) echo "Please answer y or n!";;
        esac
    done 
}

sudo_if_required() {
    if [[ $(id -u) != 0 ]]; then
        sudo "$@"
    else
        "$@"
    fi
}

print_help() {
    cat <<EOF
rebuild-initramfs: rebuild some (or all) initramfs images using dracut.

Usage: rebuild-initramfs [-h | --help] [-v | --verbose]
Command line options:
    -h, --help: prints this help message
    -v, --verbose: be more verbose
EOF
}

if [[ -t 1 ]]; then
    YELLOW="\e[33m"
    COLOROFF="\e[39m"
fi

[[ $(id -u) == 0 ]] && ([[ -z "$SUDO_UID" ]] ||
    printf "${YELLOW}WARNING:${COLOROFF} Don't run this script with sudo. This script will call out to sudo if required.\n" >&2)

for arg in "$@"
do
    case $arg in
        -v|--verbose)
            verbose=1
            echo "Running in verbose mode."
            shift;;
        -h|--help)
            print_help
            exit;;
    esac
done

mapfile -t kernels < <(ls -d /usr/lib/modules/*/)

for k in "${kernels[@]}"; do
    version=$(basename "$k")
    base=$(pacman -Qoq "$k" 2>/dev/null | head -n -1)

    if [[ "$base" == "" ]]; then
        [[ -z $verbose ]] || >&2 echo "${version} is detected, but it is not an installed kernel!"
        break
    fi
    
    printf 'Rebuild initramfs for: %s...\n' "$base"
    prompt

    if [[ "$do_build" == "1" ]]; then
        echo "Running: dracut -f -N /boot/initramfs-${base}.img --kver ${version}"
        sudo_if_required dracut -f -N /boot/initramfs-"${base}".img --kver "${version}"
        echo "Running: dracut -f --no-hostonly-cmdline /boot/initramfs-${base}-fallback.img --kver ${version}"
        sudo_if_required dracut -f --no-hostonly-cmdline /boot/initramfs-"${base}"-fallback.img --kver "${version}"
    else
        [[ -z $verbose ]] || echo "Not rebuilding initramfs image for ${version}."
    fi 
done

