#!/bin/bash -e

kernels=()
all=0
sign=0
key_path=
cert_path=

if [[ -f /etc/rebuild-initramfs.conf ]]; then
    source /etc/rebuild-initramfs.conf

    if [[ "${key_path}" != "" ]] && [[ "${cert_path}" != "" ]]; then
        sign=1
    fi
fi

while read -r line; do
    if [[ ${line} != */vmlinuz ]]; then
        # triggers when it's a change to /usr/lib/dracut/* or systemd
        all=1
        continue
    fi

    if ! read -r pkgbase > /dev/null 2>&1 < "${line%/vmlinuz}/pkgbase"; then
        continue
    fi

    # always install the kernel
    install -Dm644 "${line}" "/boot/vmlinuz-${pkgbase}"

    kernels+=("${pkgbase}")
done

args="-k"

if (( sign )); then
    args+=" --key ${key_path} --cert ${cert_path}"
fi

if ! (( all )) && (( ${#kernels[@]} )); then
    args+=" ${kernels[*]}"
fi

rebuild-initramfs "${args}"
